version: "2"
run:
  modules-download-mode: readonly
  tests: false
linters:
  disable:
    - unused
    - staticcheck
  enable:
    - gosec
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
