version: '2'
services:

  consul:
    image: bitnami/consul:latest
    volumes:
    - consul_data:/bitnami
    ports:
    - '8300:8300'
    - '8301:8301'
    - '8301:8301/udp'
    - '8500:8500'
    - '8600:8600'
    - '8600:8600/udp'

  vault:
    depends_on:
      - consul
#   Venafi plugin image
    image: "venafi/vault-venafi:0.1.120"
#   Uncomment if you want to use compose in dev mode
#    build: .
    hostname: "vault"
    links:
      - "consul:consul"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    extra_hosts:
    - "ha-tpp1.sqlha.com:192.168.6.23"
    volumes:
#    If you want to use trust bundle file option
       - /tmp/chain.pem:/tmp/chain.pem
#    Uncomment this mounts if you want to use developement version of the plugin
#      - ./scripts/tools:/tools
#      - ./scripts/config/vault:/config
#      - ./scripts/config/vault/policies:/policies
#      - ./bin:/vault_plugin
#      - ./Makefile:/Makefile
    entrypoint: /tools/wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/vault-config-with-consul.hcl -log-level=debug
#TODO: this is a workaround to avoid internal network conflict, need to find a better solution when netwrok will not be in docker-compose file.
#networks:
#  default:
#    ipam:
#      driver: default
#      config:
#      - subnet: "192.168.84.1/24"

volumes:
  consul_data:
    driver: local